#!/bin/sh
set -e

tlmgr update --self --all
tlmgr install collection-basic collection-latex collection-latexrecommended collection-fontsrecommended latexmk
tlmgr install fbb collection-luatex ms pgf pgfplots standalone times txfonts xcolor
tlmgr install ly1 ifetex cabin fontaxes mweights inconsolata enumitem menukeys xstring adjustbox collectbox
tlmgr install relsize catoptions framed upquote 