# Image
TAG := medium

# Build Args
USER := docker
SCHEME=scheme-medium
BUILD_PARAMS := --build-arg USER="${USER}" --build-arg SCHEME="${SCHEME}"

# Filepath
PATH_DOCKER := $(PATH_ROOT)/src
PATH_DOCKERFILE := $(PATH_DOCKER)/Dockerfile